# Definition for the intruder instance type
# Specifies which bootstrap script to run to set up this instance type

heat_template_version: 2014-10-16

parameters:
  Flavor:
    description: Flavor of the intruder server
    type: string
    default: m1.small
  KeyName:
    description: Name of an existing ssh keypair
    type: string
  PrivateNet:
    description: Private network for pnda deployment
    type: string
  PrivateSubnet:
    description: Private network for pnda deployment
    type: string
  PublicNet:
    description: Private network for pnda deployment
    type: string
  Image:
    type: string
  name:
    type: string
  private_key:
    type: string
  cluster_name:
    type: string
  pnda_secgroup:
    type: string

resources:
  sec_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Intruder SecurityGroup
      name:
        str_replace:
          template: cname-intruder
          params :
            cname: { get_param: cluster_name }
      rules:
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 22
          port_range_max: 22

  port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: PrivateNet }
      fixed_ips:
        - subnet_id: { get_param: PrivateSubnet }
      security_groups: [{ get_resource: sec_group },{ get_param: pnda_secgroup }]

  floatingIP:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: PublicNet }
      port_id: { get_resource: port}

  intruder_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config:
        str_replace:
          template: {get_file: scripts/bastion_install.sh }
          params:
            $private_key$: { get_param: private_key }
            $keyname$: { get_param: 'OS::stack_name' }
  server:
    type: OS::Nova::Server
    depends_on: floatingIP
    properties:
      name: { get_param: name }
      image: { get_param: Image }
      flavor: { get_param: Flavor}
      key_name: { get_param: KeyName }
      networks:
        - port: { get_resource: port }
      user_data_format: SOFTWARE_CONFIG
      user_data: {get_resource: intruder_config}

outputs:
  server_resource:
    description: Heat resource handle for the Nova compute server
    value:
      {get_resource: server}
